swagger: '2.0'
info:
  version: 2.0.0
  title: REST service for external systems
basePath: /api
tags:
  - name: sample
  - name: posDevice
  - name: posDeviceLocation
paths:
  /sample:
    get:
      tags:
        - sample
      summary: Sample url
      description: 'sample request. Do nothing.'
      operationId: getSample
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Sample'
  /posDevice/getInfoByVendorCodeNameAndSerialNumber:
    get:
      tags:
        - posDevice
      summary: Get device info by vendor 
      description: ''
      operationId: getInfoByVendorCodeNameAndSerialNumber
      produces:
        - application/json
      parameters:
        - in: query
          name: vendor
          type: string
          required: true
        - in: query
          name: serialNumber
          type: string
          required: true
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/PosDeviceInfo'
  /posDeviceLocation/getPosTerminalDevices:
    get:
      tags:
        - posDeviceLocation
      summary: Get device location info by terminalId 
      description: ''
      operationId: getPosTerminalDevices
      produces:
        - application/json
      parameters:
        - in: query
          name: terminalId
          type: string
          required: true
          description: TID
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/PosDeviceLocationInfo'
security:
  - OAuth2: [read]
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: application
    description: OAuth 2.0 with Client Credentias Grant type
    tokenUrl: 'https://any-domain/oauth/token'
    scopes:
      'read': Grant read-only access to all api
definitions:
  Sample:
    type: object
    properties:
      foo:
        type: string
      timestamp:
        type: integer
        format: int64
  PosDeviceInfo:
    type: object
    properties:
      type:
        type: string
      modelName:
        type: string
      networkType:
        type: string
      contactlessModuleSupport:
        type: boolean
      pciVersion:
        type: string
      secureLink:
        type: boolean
      vendorCode:
        type: string
      technology:
        type: string
      status:
        type: string
      class:
        type: string
  PosDeviceLocationInfo:
    type: object
    properties:
      terminalId:
        type: string
      posDevice:
        $ref: '#/definitions/DeviceInfo'
      pinPad:
        $ref: '#/definitions/DeviceInfo'
  DeviceInfo:
    type: object
    properties:
      serialNumber:
        type: string
      vendor:
        type: string
